import Head from 'next/head'
import ArticleList from '../components/Article';
import { server } from '../config';

export default function Home({ articles }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>


      <ArticleList articles={articles} />
    </div>
  )
}


// data fetching
// - getStaticProps, getStaticPath, getServerSideProps


export const getStaticProps = async () => {
  const res = await fetch(`${server}/api/articles`);
  const articles = await res.json();

  return {
    props: {
      articles
    }
  }
}