import Head from 'next/head'
import ArticleList from '../components/Article';

export default function Home({articles}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>


      <ArticleList articles={articles} />
    </div>
  )
}


// data fetching
// - getStaticProps, getStaticPath, getServerSideProps


export const getStaticProps = async () => {
  const res = await fetch(`https://jsonplaceholder.typicode.com/posts?_limit=6`);
  const articles = await res.json();

  return {
    props: {
      articles
    }
  }
}